### ISSUE TITLE
[REQUEST] Ghostfolio

### ISSUE THREAD

**Issue by bttfw** [pi-hosted/pi-hosted#106]
Is it possible to add https://github.com/ghostfolio/ghostfolio to the apps ?

**Comment by Macleykun** [comment]
Has to be deployed as a stack:
```
version: '3.7'
services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=prefer
      NODE_ENV: production
      REDIS_HOST: 'redis'
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 3333:3333

  postgres:
    image: postgres:12
    env_file:
      - ../.env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'

volumes:
  postgres:
```
need to also get the env vars from the file into the compose/stack and then should be all good.
i'll see when i'll get around it sometime.
