### ISSUE TITLE
[REQUEST] Populate Dashy config file with sample section to prevent error

### ISSUE THREAD

**Issue by demosthien** [pi-hosted/pi-hosted#122]
I deployed the Dashy dashboard.
I used the provided script before deploying the container in Portainer.
After deploying the container I opened Dashy and attempted to create a new section via the UI "interactive editor" but the details would not save.
I noticed other installs of Dashy (YouTube etc) generally start with a provided section called "Getting Started", this section was not present in my version (I assume the Pi-Hosted script only creates an empty config file).
I reviewed the config details via the update configuration option (using the internal code editor) and noticed a warning triangle stating something about missing an expected "section".
I found a code sample from the Dashy dev which included a snippet for the section and I added into my config (see code below) and that "Getting Started" section now appears on my dashboard.
See attached images for the location where I placed the snippet.
This also seems to have fixed the issue of not being able to create new sections.
It might be worth having the Pi-Hosted script create a populated config instead of an empty one or alternatively provide basic JSON code for a user to copy/paste into the config file after running the script?

[Code below is from here.](https://gist.github.com/Lissy93/000f712a5ce98f212817d20bc16bab10#file-example-1-getting-started-conf-yml)

`  "sections": [
    {
      "name": "Getting Started",
      "icon": "fas fa-rocket",
      "items": [
        {
          "title": "Dashy Live",
          "description": "Development a project management links for Dashy",
          "icon": "https://i.ibb.co/qWWpD0v/astro-dab-128.png",
          "url": "https://live.dashy.to/",
          "target": "newtab"
        },
        {
          "title": "GitHub",
          "description": "Source Code, Issues and Pull Requests",
          "url": "https://github.com/lissy93/dashy",
          "icon": "favicon"
        },
        {
          "title": "Docs",
          "description": "Configuring & Usage Documentation",
          "provider": "Dashy.to",
          "icon": "far fa-book",
          "url": "https://dashy.to/docs"
        },
        {
          "title": "Showcase",
          "description": "See how others are using Dashy",
          "url": "https://github.com/Lissy93/dashy/blob/master/docs/showcase.md",
          "icon": "far fa-grin-hearts"
        },
        {
          "title": "Config Guide",
          "description": "See full list of configuration options",
          "url": "https://github.com/Lissy93/dashy/blob/master/docs/configuring.md",
          "icon": "fas fa-wrench"
        },
        {
          "title": "Support",
          "description": "Get help with Dashy, raise a bug, or get in contact",
          "url": "https://github.com/Lissy93/dashy/blob/master/.github/SUPPORT.md",
          "icon": "far fa-hands-helping"
        }
      ]
    }
  ]
}`

<img width="782" alt="Screen Shot 2022-12-03 at 18 35 10" src="https://user-images.githubusercontent.com/7120221/205457239-7a89995b-e60c-4e2b-b153-6b19b0aaa0de.png">

<img width="782" alt="Screen Shot 2022-12-03 at 18 35 24" src="https://user-images.githubusercontent.com/7120221/205457248-0c90f768-8556-4ea0-a684-468250fe9ff4.png">

**Comment by Macleykun** [comment]
I'm not sure where your editting this, but i've tried it and got the following:
```
    - name: widgets
      displayData:
        sortBy: default
        rows: 1
        cols: 1
        collapsed: false
        hideForGuests: false
      widgets:
      - type: clock
        options:
          timeZone: Europe/London
          format: en-GB
          hideDate: false
      - type: synology-download
        options:
          hostname: url
          username: name
          password: pass
```
Now this was done in: local-conf.yml which is located here: `/portainer/Files/AppData/Config/Dashy`
To add widgets, i personally advice to keep it simple as it isn't possible to do this in the UI yet (so i consider this to be BETA/not userfriendly yet).

It could be possible, but if a user doesn't want this widget, they can't remove it from the UI and have to get into the file to remove it.

I think personally it's better to not fillup the config with widgets and instead suggest users to use my example or wait for proper UI support.

`sudo vim /portainer/Files/AppData/Config/Dashylocal-conf.yml`
```
appConfig:
  layout: auto
  iconSize: medium
  language: nl
  theme: adventure
pageInfo:
  title: Dashy
  description: ''
  navLinks: []
  footerText: ''
sections:
  - name: General
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: HomeAssistant
        description: Home automation
        icon: hl-home-assistant
        url: homeurlexample
        target: newtab
        statusCheck: true
        id: 0_702_homeassistant
  - name: widgets
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    widgets:
    - type: clock
      options:
        timeZone: Europe/London
        format: en-GB
        hideDate: false
    - type: synology-download
      options:
        hostname: url
        username: name
        password: pass
```

This example makes two colums with one normale item and two widgets in the other.
