### ISSUE TITLE
[QUESTION] How to successfully setup Paperless-NGX?

### ISSUE THREAD

**Issue by charles-spurgeon** [pi-hosted/pi-hosted#130]
**Question**
How can I log-in to the Paperless-NGX web interface–this is from the App Template in the Pi-Hosted template.

**Context**
Everything deploys (seemingly) correctly, but logging-in to the web interface is consistently unsuccessful–constant authentication errors with correct credentials.

This even after setting the environment variables:
PAPERLESS_ADMIN_USER
PAPERLESS_ADMIN_PASSWORD

However, it seems to be necessary to set these up during initial deployment–which is not an option–so redeploying the container doesn't seem to help.

I looked to see if there was some default password but I couldn't find one.

Additionally, createsuperuser is not installed for django-admin, so that does not work from the console.

**Comment by Macleykun** [comment]
heya, i can add those two env vars so the user can specify it.
I tried to login a couple of times back to back, but it seems to work fine for me, for now.

I could create a super user, but i'm not sure how to use it/what it's purpose is really.

**Comment by BaderMaiss** [comment]
I haven't deployed it from the template but here's the docker compose file that you can deploy as a stack directly from Portainer:


```
version: "3.4"
services:
  broker:
    container_name: paperless_broker
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/Paperless-ngx/redisdata:/data

  webserver:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8020:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /portainer/Files/AppData/Config/Paperless-ngx/data:/usr/src/paperless/data
      - /{the path paperless will use to store your documents}:/usr/src/paperless/media
      - /portainer/Files/AppData/Config/Paperless-ngx/export:/usr/src/paperless/export
      - /{the path paperless will read documents from}:/usr/src/paperless/consume
    
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      USERMAP_UID: 1000 # Put your user ID
      USERMAP_GID: 100 # Put your user group ID
      PAPERLESS_SECRET_KEY: gLhZqyvB7K855mxby8PH # Your secret key
      PAPERLESS_TIME_ZONE: Europe/Rome # Your timezone
      PAPERLESS_OCR_LANGUAGE: ita # OCR default language

      # Additional settings for slow systems
      PAPERLESS_OCR_MODE: skip_noarchive
      PAPERLESS_OCR_CLEAN: none
      PAPERLESS_OCR_PAGES: 1
      PAPERLESS_ENABLE_NLTK: false
      PAPERLESS_TASK_WORKERS: 2
      PAPERLESS_THREADS_PER_WORKER: 1
```
Change the paths in curly braces to the ones inside of your host and the environment variables to your liking.

_Side note: I'm not using a Raspberry Pi._
