### ISSUE TITLE
[REQUEST] Kavita - open source reading server

### ISSUE THREAD

**Issue by badermaiss** [pi-hosted/pi-hosted#134]
This service could be added to the template. I got it setup up recently and I'm enjoying it so far.

![](https://www.kavitareader.com/img/features/search_v0.5.4.PNG)

Docker-compose file example provided by the official documentation: [Link](https://wiki.kavitareader.com/en/install/docker-install).
Preview:
```
version: '3.9'
services:
    kavita:
        image: kizaing/kavita:latest    # Change latest to nightly for latest develop builds (can't go back to stable)
        container_name: kavita
        volumes:
            - ./manga:/manga            # Manga is just an example you can have the name you want. See the following
            - ./comics:/comics          # Use as many as you want
            - ./books:/books            #
            - ./data:/kavita/config     # Change './data if you want to have the config files in a different place.
                                        # /kavita/config must not be changed
        environment:
            - TZ=Your/Timezone
        ports:
            - "5000:5000" # Change the public port (the first 5000) if you have conflicts with other services
        restart: unless-stopped
```

Links:
[Github](https://github.com/Kareadita/Kavita)
[Website](https://www.kavitareader.com/)
[Demo](https://demo.kavitareader.com/login) `Username: demouser, Password: Demouser64`
